version: 2.1
executors:
  collector-exec:
    docker:
      - image: mcr.microsoft.com/dotnet/core/sdk:2.2
    working_directory: ~/src/Collector
jobs:
  build:
    executor: collector-exec
    steps:
      - checkout
      - run:
        name: Restore packages
        command: dotnet restore
      - run:
        name: Build app
        command: dotnet build