version: 2
jobs:
  build:
    docker:
        - image: mcr.microsoft.com/dotnet/core/sdk:3.0

    working_directory: ~/repo/src/Collector
    
    steps:
      - checkout:
          path: ~/repo
      - run:
          name: Restore packages
          command: 
            dotnet restore
      - run:
          name: Build app
          command: 
            dotnet build