version: 2
jobs:
  checkout-project:
    docker:
        - image: mcr.microsoft.com/dotnet/core/sdk:2.2

    steps:
      - checkout

  build:
    docker:
          - image: mcr.microsoft.com/dotnet/core/sdk:2.2

    working_directory: ~/src/Collector
    
    steps:
      - run:
          name: Restore packages
          command: 
            dotnet restore
      - run:
          name: Build app
          command: 
            dotnet build