version: 2.1

jobs:
  build-collector:
    docker:
        - image: davi7816/dotnetcore-docker:3.0

    working_directory: ~/repo/src/Collector

    parameters:
      tag:
        type: string
        default: "0.${CIRCLE_BUILD_NUM}"

    steps:
      - checkout:
          path: ~/repo
      - run:
          name: Restore packages
          command: 
            dotnet restore
      - run:
          name: Build app
          command: 
            dotnet build -c Release -o publish
      - setup_remote_docker
      - run:
          name: Deploy app
          command: |
            docker build -t davi7816/si-collector:<< parameters.tag >> .
            echo $DockerPass | docker login -u $DockerUser --password-stdin 
            docker push davi7816/si-collector:<< parameters.tag >>
            ssh -o StrictHostKeyChecking=no cicleci@167.172.98.57 "/bin/bash ./deploy_app.sh davi7816/si-collector:<< parameters.tag >>"

  build-admin:
    docker:
        - image: davi7816/dotnetcore-docker:3.0

    working_directory: ~/repo/src/Admin
    
    parameters:
      tag:
        type: string
        default: "0.${CIRCLE_BUILD_NUM}"

    steps:
      - checkout:
          path: ~/repo
      - run:
          name: Restore packages
          command: 
            dotnet restore
      - run:
          name: Build app
          command: 
            dotnet build -c Release -o publish
      - setup_remote_docker
      - run:
          name: Deploy app
          command: |
            docker build -t davi7816/si-admin:<< parameters.tag >> .
            echo $DockerPass | docker login -u $DockerUser --password-stdin 
            docker push davi7816/si-admin:<< parameters.tag >>
  
  build-client:
    docker:
        - image: davi7816/dotnetcore-docker:3.0

    working_directory: ~/repo/src/Client
    
    parameters:
      tag:
        type: string
        default: "0.${CIRCLE_BUILD_NUM}"

    steps:
      - checkout:
          path: ~/repo
      - run:
          name: Restore packages
          command: 
            dotnet restore
      - run:
          name: Build app
          command: 
            dotnet build -c Release -o publish
      - setup_remote_docker
      - run:
          name: Deploy app
          command: |
            docker build -t davi7816/si-client:<< parameters.tag >> .
            echo $DockerPass | docker login -u $DockerUser --password-stdin 
            docker push davi7816/si-client:<< parameters.tag >>

workflows:
  version: 2.1
  si-worflow:
    jobs:
      - build-collector
      - build-admin
      - build-client
