version: 2
jobs:
  build:
    docker:
        - image: davi7816/dotnetcore-docker:3.0

    working_directory: ~/repo/src/Collector
    
    steps:
      - checkout:
          path: ~/repo
      - run:
          name: Restore packages
          command: 
            dotnet restore
      - run:
          name: Build app
          command: 
            dotnet build -c Release -o publish
      - setup_remote_docker:
      - run:
          name: Deploy app
          command: |
            docker build -t davi7816/si-collector:latest .
            echo $DockerPass | docker login -u $DockerUser --password-stdin 
            docker push davi7816/si-collector:latest
            ssh -o StrictHostKeyChecking=no cicleci@167.172.98.57 "/bin/bash ./deploy_app.sh davi7816/si-collector:latest" 